import {
  ActivityIcon,
  AwardIcon,
  BellIcon,
  BookIcon,
  BookmarkIcon,
  BookOpenIcon,
  BoxIcon,
  BriefcaseIcon,
  CalendarIcon,
  CameraIcon,
  ClipboardIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  CpuIcon,
  DatabaseIcon,
  FileTextIcon,
  FlagIcon,
  FolderIcon,
  GamepadIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  GridIcon,
  HammerIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  LayersIcon,
  LayoutIcon,
  LightbulbIcon,
  LinkIcon,
  LockIcon,
  type LucideIcon,
  MailIcon,
  MapPinIcon,
  MessageCircleIcon,
  MonitorIcon,
  MusicIcon,
  NewspaperIcon,
  PackageIcon,
  PaletteIcon,
  PenToolIcon,
  PieChartIcon,
  PlaneIcon,
  RocketIcon,
  SearchIcon,
  SettingsIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  StarIcon,
  TagIcon,
  TargetIcon,
  ToolboxIcon,
  TrendingUpIcon,
  TrophyIcon,
  TruckIcon,
  UmbrellaIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  ZapIcon,
} from "lucide-react";

export const COLLECTION_ICONS: Record<string, LucideIcon> = {
  Folder: FolderIcon,
  Bookmark: BookmarkIcon,
  Heart: HeartIcon,
  Star: StarIcon,
  Home: HomeIcon,
  Briefcase: BriefcaseIcon,
  Code: CodeIcon,
  Lightbulb: LightbulbIcon,
  Music: MusicIcon,
  Palette: PaletteIcon,
  ShoppingCart: ShoppingCartIcon,
  Trophy: TrophyIcon,
  BookOpen: BookOpenIcon,
  Camera: CameraIcon,
  Coffee: CoffeeIcon,
  Gamepad: GamepadIcon,
  GraduationCap: GraduationCapIcon,
  Hammer: HammerIcon,
  Image: ImageIcon,
  Mail: MailIcon,
  MapPin: MapPinIcon,
  MessageCircle: MessageCircleIcon,
  Monitor: MonitorIcon,
  Newspaper: NewspaperIcon,
  PenTool: PenToolIcon,
  Plane: PlaneIcon,
  Rocket: RocketIcon,
  Shield: ShieldIcon,
  Smartphone: SmartphoneIcon,
  Target: TargetIcon,
  TrendingUp: TrendingUpIcon,
  Users: UsersIcon,
  Video: VideoIcon,
  Wallet: WalletIcon,
  Zap: ZapIcon,
  Activity: ActivityIcon,
  Award: AwardIcon,
  Bell: BellIcon,
  Book: BookIcon,
  Box: BoxIcon,
  Calendar: CalendarIcon,
  Clipboard: ClipboardIcon,
  Cloud: CloudIcon,
  Cpu: CpuIcon,
  Database: DatabaseIcon,
  FileText: FileTextIcon,
  Flag: FlagIcon,
  Gift: GiftIcon,
  Globe: GlobeIcon,
  Grid: GridIcon,
  Layers: LayersIcon,
  Layout: LayoutIcon,
  Link: LinkIcon,
  Lock: LockIcon,
  Package: PackageIcon,
  PieChart: PieChartIcon,
  Search: SearchIcon,
  Settings: SettingsIcon,
  Tag: TagIcon,
  ToolBox: ToolboxIcon,
  Truck: TruckIcon,
  Umbrella: UmbrellaIcon,
};

export const AVAILABLE_ICONS = Object.entries(COLLECTION_ICONS).map(
  ([name, icon]) => ({
    name,
    icon,
  }),
);

export function getCollectionIcon(iconName: string | null): LucideIcon {
  if (!iconName || !COLLECTION_ICONS[iconName]) {
    return FolderIcon;
  }
  return COLLECTION_ICONS[iconName];
}
